### ISSUE TITLE
Ability to choose  among English variants: American & British 

### ISSUE THREAD

**Issue by marreromarco** [realmayus/anki_forvo_dl#31] opened 2021-07-13 02:06 UTC
Hello ! Would it be possible to add the choice of selecting:
- American English
- British English

Forvo also has a category for "Other" variants.

Would it be nice if we could choose among the desired variant because it is confusing for second language learners to mix British and American pronunciations.

**Comment by realmayus** [comment] 2021-07-15 21:28
Thanks for the suggestion! Since the two variants are spoken in America/the UK respectively, this could be realized by a country selection feature 👍 
This makes this a duplicate of #11. I plan to implement such a feature in the near future.

**Closed by realmayus** 2021-07-15 21:28 UTC
