### ISSUE TITLE
Updated Version doesnt work

### ISSUE THREAD

**Issue by Saoshyant1** [realmayus/anki_forvo_dl#43] opened 2021-09-25 20:03 UTC
When I originally downloaded forvo  dl it worked perfectly  but when I updated it the updated version doesn't work Could you give me the code for an older version please
[
![screen-21 45 15 25 09 2021](https://user-images.githubusercontent.com/85819390/134785599-493cf4b4-2bbe-4ff2-9291-e2cc886f29b8.png)
](url)

**Comment by liesaliesa** [comment] 2021-09-25 22:00
Same here. Error message is also the same as above

**Comment by realmayus** [comment] 2021-09-25 22:16
Thanks for the report; I'll look into it ASAP.

**Comment by aronvandepol** [comment] 2021-09-26 09:20
Doesn't work here either on Mac.

**Comment by diklape** [comment] 2021-09-26 10:21
Extension no longer works after update

**Comment by Calvin-Xu** [comment] 2021-09-27 00:00
I think it's caused by a simple import issue in `ConfigManager.py` and `GuiElements.py`. Tested the fix on Mac Anki.

**Comment by realmayus** [comment] 2021-09-27 13:37
Closed in 54bce32895138ff902d8bc68ce4307e77fe0984b

**Comment by atomicptr** [comment] 2021-09-27 14:42
I still get this when hitting the forvo dl button in a note:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-27 16:36:48
Add-ons possibly involved: ⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 541, in handler
  File "aqt/editor.py", line 524, in <lambda>
  File "/home/christopher/.local/share/Anki2/addons21/858591644/__init__.py", line 205, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "/home/christopher/.local/share/Anki2/addons21/858591644/__init__.py", line 113, in add_pronunciation
    d = LanguageSelector(editor.parentWindow, mw.col.decks.get(deck_id)["name"])
  File "/home/christopher/.local/share/Anki2/addons21/858591644/src/LanguageSelector.py", line 11, in __init__
    from anki_forvo_dl import asset_dir
ModuleNotFoundError: No module named 'anki_forvo_dl'
```

and this exception gets also thrown if you try to open Tools > anki-forvo-dl > Preferences

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-27 16:36:48
Add-ons possibly involved: ⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "/home/christopher/.local/share/Anki2/addons21/858591644/__init__.py", line 226, in on_pref_btn_click
    config_manager = ConfigManager(config)
  File "/home/christopher/.local/share/Anki2/addons21/858591644/src/ConfigManager.py", line 17, in __init__
    from anki_forvo_dl import asset_dir
ModuleNotFoundError: No module named 'anki_forvo_dl'
```

**Comment by realmayus** [comment] 2021-09-27 17:03
Thanks for the report, I just published a version fixing this.

**Closed** 2021-09-27 17:03 UTC
